# output dir will be created by hydra
data_dir: /global/cfs/projectdirs/m4958/data/JetSSL/inputs_h5
output_dir: /global/cfs/projectdirs/m4958/data/JetSSL/outputs

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
